import { toPng } from 'html-to-image';
import jsPDF from 'jspdf';
import { format } from 'date-fns';

export async function generatePDFReport(elementId: string, title: string) {
  const element = document.getElementById(elementId);
  if (!element) throw new Error("Element not found for PDF generation");

  try {
    // 1. Capture the element as an image
    // Temporarily apply a style to ensure maps render fully if needed
    const dataUrl = await toPng(element, {
      quality: 0.95,
      backgroundColor: '#ffffff',
      pixelRatio: 2, // High resolution
    });

    // 2. Initialize jsPDF (A4 page, portrait)
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    
    // 3. Draw Header
    pdf.setFillColor(15, 23, 42); // slate-900 background
    pdf.rect(0, 0, pageWidth, 25, 'F');
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("SPETRO", 15, 16);
    
    pdf.setTextColor(0, 212, 170); // teal-500
    pdf.setFontSize(10);
    pdf.text("Geoportal Analysis", 45, 16);
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(12);
    const dateStr = format(new Date(), 'MMM dd, yyyy');
    pdf.text(dateStr, pageWidth - 15, 16, { align: 'right' });
    
    // 4. Draw Title
    pdf.setTextColor(15, 23, 42);
    pdf.setFontSize(16);
    pdf.text(`${title} Report`, 15, 40);
    
    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139); // slate-500
    pdf.text(`Generated by Google Earth Engine | SPETRO Automated Analysis System`, 15, 46);

    // 5. Draw Image
    // A4 is 210 x 297 mm
    const imgProps = pdf.getImageProperties(dataUrl);
    const margin = 15;
    const maxImgWidth = pageWidth - (margin * 2);
    const maxImgHeight = pageHeight - 60 - margin; // 60 is top offset

    let imgWidth = maxImgWidth;
    let imgHeight = (imgProps.height * imgWidth) / imgProps.width;

    if (imgHeight > maxImgHeight) {
      imgHeight = maxImgHeight;
      imgWidth = (imgProps.width * imgHeight) / imgProps.height;
    }

    pdf.addImage(dataUrl, 'PNG', margin, 55, imgWidth, imgHeight);
    
    // 6. Draw Footer
    pdf.setFontSize(8);
    pdf.setTextColor(148, 163, 184); // slate-400
    pdf.text(`© ${new Date().getFullYear()} SPETRO Geoportal. All rights reserved.`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    
    // 7. Save
    const filename = `SPETRO_${title.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`;
    pdf.save(filename);
    
    return true;
  } catch (error) {
    console.error("Failed to generate PDF:", error);
    throw error;
  }
}
